/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Book: { // root type
    author: string; // String!
    id: number; // Int!
    title: string; // String!
    translator?: string | null; // String
  }
  Invite: { // root type
    email: string; // String!
    id: number; // Int!
  }
  Mutation: {};
  Query: {};
  User: { // root type
    birthday?: string | null; // String
    city?: string | null; // String
    country?: string | null; // String
    email: string; // String!
    firstname: string; // String!
    id: number; // Int!
    lastname: string; // String!
    password: string; // String!
    phonenumber?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Book: { // field return type
    author: string; // String!
    id: number; // Int!
    title: string; // String!
    translator: string | null; // String
    users: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  Invite: { // field return type
    email: string; // String!
    id: number; // Int!
    inviter: NexusGenRootTypes['User'] | null; // User
  }
  Mutation: { // field return type
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    newBook: NexusGenRootTypes['Book']; // Book!
    newInvite: NexusGenRootTypes['Invite']; // Invite!
    signup: NexusGenRootTypes['AuthPayload']; // AuthPayload!
  }
  Query: { // field return type
    inviteSearch: NexusGenRootTypes['Invite'][]; // [Invite!]!
  }
  User: { // field return type
    birthday: string | null; // String
    books: Array<NexusGenRootTypes['Book'] | null> | null; // [Book]
    city: string | null; // String
    country: string | null; // String
    email: string; // String!
    firstname: string; // String!
    id: number; // Int!
    invitation: Array<NexusGenRootTypes['Invite'] | null> | null; // [Invite]
    lastname: string; // String!
    password: string; // String!
    phonenumber: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Book: { // field return type name
    author: 'String'
    id: 'Int'
    title: 'String'
    translator: 'String'
    users: 'User'
  }
  Invite: { // field return type name
    email: 'String'
    id: 'Int'
    inviter: 'User'
  }
  Mutation: { // field return type name
    login: 'AuthPayload'
    newBook: 'Book'
    newInvite: 'Invite'
    signup: 'AuthPayload'
  }
  Query: { // field return type name
    inviteSearch: 'Invite'
  }
  User: { // field return type name
    birthday: 'String'
    books: 'Book'
    city: 'String'
    country: 'String'
    email: 'String'
    firstname: 'String'
    id: 'Int'
    invitation: 'Invite'
    lastname: 'String'
    password: 'String'
    phonenumber: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    newBook: { // args
      author: string; // String!
      title: string; // String!
      translator?: string | null; // String
    }
    newInvite: { // args
      email: string; // String!
    }
    signup: { // args
      birthday?: string | null; // String
      city?: string | null; // String
      country?: string | null; // String
      email: string; // String!
      firstname: string; // String!
      lastname: string; // String!
      password: string; // String!
      phonenumber?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}